apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-dep-replica
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: sample_fast_api:v2
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: app-dep-service
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000

