apiVersion: v1
kind: Secret
metadata:
  name: fastapi-secret
type: Opaque
stringData:
  API_KEY: dGVzdGluZzEyMw==

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-config
data:
  APP_ENV: production
  DEBUG: "false"
  LOG_LEVEL: info
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-dep-replica
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: sample_fast_api:v3
        ports:
        - containerPort: 8080
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: fastapi-secret
              key: API_KEY
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: fastapi-config
              key: APP_ENV

---
apiVersion: v1
kind: Service
metadata:
  name: app-dep-service
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000

